org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# Published coordinates (com.vanniktech.maven.publish)
GROUP=com.rtcstack
VERSION_NAME=1.0.2
POM_URL=https://github.com/radioBros/RTCstack
POM_LICENSE_NAME=MIT
POM_LICENSE_URL=https://opensource.org/licenses/MIT
